env:
    - TWISTED=Twisted==13.2
    - TWISTED=git+https://github.com/twisted/twisted.git

language: python

python:
    - 2.7
    - pypy

install:
    - pip install -q $TWISTED
    - python setup.py -q install

script: trial haddock
