env:
    - TWISTED=Twisted==13.2
    - TWISTED=git+https://github.com/twisted/twisted.git

language: python

python:
    - 2.7
    - pypy

install:
    - pip install -q $TWISTED
    - pip install coveralls
    - python setup.py -q install

script: coverage run `which trial` haddock

after_success:
    coveralls